import js from '@eslint/js'
import svelte from 'eslint-plugin-svelte'
import globals from 'globals'
import ts from 'typescript-eslint'

export default ts.config(
  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs['flat/recommended'],
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
  },
  {
    files: ['**/*.svelte'],
    languageOptions: {
      parserOptions: { parser: ts.parser },
    },
  },
  {
    rules: {
      // Empty `catch {}` is a deliberate best-effort idiom here (localStorage,
      // feature detection). Real swallowed failures use the `swallow()` helper.
      'no-empty': ['error', { allowEmptyCatch: true }],
      // Ternaries / short-circuits used purely for their side effect are an
      // intentional idiom here (e.g. `cond ? set.delete(x) : set.add(x)`).
      '@typescript-eslint/no-unused-expressions': ['error', { allowShortCircuit: true, allowTernary: true }],
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      }],
      // Opt-in SvelteKit typed-navigation API; plain string paths are fine.
      'svelte/no-navigation-without-resolve': 'off',
      // Misfires here: every flagged Set/Map is a local temporary, a
      // reassignment (`x = new Set(x)`), or the immutable store-update pattern
      // (`store.update(s => new Set(s))`) — none are reactive `$state` mutated
      // in place, which is what this rule is meant to catch. If you ever do keep
      // a Set/Map in `$state` and mutate it, use SvelteSet/SvelteMap.
      'svelte/prefer-svelte-reactivity': 'off',
      // Opt-in modernization (writable `$derived`). The candidates are editable
      // form inputs seeded from a store; migrating changes their reset timing,
      // which needs a manual UI check — left off rather than changed blind.
      'svelte/prefer-writable-derived': 'off',
    },
  },
  {
    // Generated by ts-rs (`just gen-types`); not ours to lint. Build outputs too.
    ignores: ['build/', '.svelte-kit/', 'dist/', 'src/lib/generated/', 'src/lib/bip39_words.ts'],
  },
)
