// Many of these types are the source of the frontend's TypeScript definitions,
// generated by ts-rs under the `ts` feature (`just gen-types` → frontend
// src/lib/generated/). Convention: any 64-bit money field must carry
// `#[cfg_attr(feature = "ts", ts(type = "number"))]`, otherwise ts-rs emits
// `bigint` and breaks the frontend — Bitcoin amounts stay well under JS's
// safe-integer ceiling, and the UI treats sats as `number`.
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
#[cfg_attr(feature = "ts", derive(ts_rs::TS), ts(export))]
pub enum InputKind {
    Address,
    Xpub,
    Ypub,
    Zpub,
    Taproot,
    Multisig,
    SilentPayments,
    /// A raw output descriptor imported as-is — miniscript or a non-standard
    /// shape that doesn't map onto the other single-sig / multisig kinds.
    Descriptor,
}

/// One discovered output for a Silent Payments wallet. Populated by the SP
/// scanner subscription; persisted to `sp_outputs.json` so matches survive
/// restart. The `t_n` tweak is what makes the output spendable — paired with
/// the spend secret at send time it reproduces the per-output private key.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpOutputRecord {
    pub txid: String,
    pub vout: u32,
    pub height: u32,
    pub value_sats: u64,
    /// Hex-encoded P2TR scriptPubKey (`OP_1 OP_PUSHBYTES_32 <x-only-key>`).
    pub script_pubkey_hex: String,
    /// 32-byte x-only Taproot output key as hex — the recipient-derived key.
    pub output_xonly_hex: String,
    /// Hex-encoded per-output tweak (`t_n`). Needed at send time alongside the
    /// spend secret to derive the spending private key for this UTXO.
    pub tweak_t_n_hex: String,
    /// The original `tweak_key` Frigate gave us (`input_hash * Σ input_pubkeys`).
    /// Recorded for verification/audit.
    pub frigate_tweak_hex: String,
    /// BIP-352 label index (`m`) that matched, or `None` for the bare address.
    #[serde(default)]
    pub label_m: Option<u32>,
    pub found_at: DateTime<Utc>,
    /// Set to true when this output is spent (Phase 3 — send-side).
    #[serde(default)]
    pub spent: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS), ts(export))]
pub struct WalletEntry {
    pub id: Uuid,
    pub label: String,
    /// Raw user input (address or xpub/ypub/zpub)
    pub input: String,
    pub kind: InputKind,
    /// BDK external descriptor string
    pub external_descriptor: String,
    /// BDK internal/change descriptor string (None for single-address wallets)
    pub internal_descriptor: Option<String>,
    /// Multisig threshold (M-of-N); None for single-sig wallets
    #[serde(default)]
    pub threshold: Option<u32>,
    /// Backend this wallet syncs and broadcasts through. None = the default
    /// backend (`[backend]` in config); otherwise the id of a `[[backends]]`
    /// registry entry. Stored now; honored by the subscriber in a later phase.
    #[serde(default)]
    pub backend: Option<String>,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS), ts(export))]
pub struct Balance {
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub confirmed_sats: u64,
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub unconfirmed_sats: u64,
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub spendable_sats: u64,
    /// Mining reward outputs (coinbase) that haven't reached the 100-block
    /// maturity threshold yet. Not included in `spendable_sats`. Zero for
    /// wallets that don't mine.
    #[serde(default)]
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub immature_sats: u64,
    pub last_synced: Option<DateTime<Utc>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS), ts(export))]
pub struct TxRecord {
    pub txid: String,
    /// Positive = received, negative = sent (in sats)
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub amount_sats: i64,
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub fee_sats: Option<u64>,
    pub vsize: Option<u32>,
    pub confirmations: u32,
    pub block_height: Option<u32>,
    pub timestamp: Option<DateTime<Utc>>,
    /// True if any input signals RBF (sequence <= 0xFFFFFFFD)
    pub is_rbf: bool,
    /// True if this is a coinbase (mining reward) transaction — its sole input
    /// has no previous output and the outputs can't be spent until 100 confs.
    #[serde(default)]
    pub is_coinbase: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS), ts(export))]
pub struct AddressInfo {
    pub address: String,
    pub index: u32,
    pub kind: AddressKind,
    pub used: bool,
    pub tx_count: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[cfg_attr(feature = "ts", derive(ts_rs::TS), ts(export))]
pub enum AddressKind {
    External,
    Internal,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS), ts(export))]
pub struct UtxoRecord {
    pub txid: String,
    pub vout: u32,
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub amount_sats: u64,
    pub address: Option<String>,
    pub confirmations: u32,
    pub block_height: Option<u32>,
    /// True if the parent transaction is a coinbase (mining reward).
    #[serde(default)]
    pub is_coinbase: bool,
    /// False only for coinbase outputs with fewer than 100 confirmations.
    /// Non-coinbase UTXOs are always mature.
    #[serde(default = "default_true")]
    pub is_mature: bool,
    /// True for a Silent Payments UTXO below the dust-attack threshold: a tiny
    /// output sent to your reusable SP address to bloat or probe the wallet. The
    /// UI flags it and suggests freezing. Always false for non-SP UTXOs.
    #[serde(default)]
    pub suspected_dust: bool,
}

fn default_true() -> bool {
    true
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS), ts(export))]
pub struct BalancePoint {
    pub block_height: u32,
    pub timestamp: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub balance_sats: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct TxFees(pub HashMap<String, u64>);

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS), ts(export))]
pub struct SyncResult {
    pub wallet_id: Uuid,
    pub new_txs: usize,
    pub synced_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[cfg_attr(feature = "ts", derive(ts_rs::TS), ts(export))]
pub enum BackendKind {
    Electrum,
    Rpc,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS), ts(export))]
pub struct NodeStatus {
    pub backend: BackendKind,
    pub connected: bool,
    pub network: String,
    pub tip_height: Option<u32>,
    pub error: Option<String>,
    /// Instance is in air-gapped/offline mode (no backend connection attempted).
    #[serde(default)]
    pub offline: bool,
}

/// A user-defined coin category (privacy compartment): a named, colored tag
/// assigned to addresses (inherited by their UTXOs) and/or individual UTXOs.
/// Distinct from the freeform note label — a coin can carry both.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Category {
    pub id: String,
    pub name: String,
    /// CSS color (hex), chosen from a small palette in the UI.
    pub color: String,
}
